spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/my-db-test
    hikari:
      password:
      username: sa
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true