spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/my-db-test
    hikari:
      password:
      username: sa
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true

  openai:
    api:
      url: https://api.openai.com/v1/chat/completions
      key: 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